### ISSUE TITLE
Abandonware

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [yene/Third-Party-Blocker.safariextension#2]
Why isn’t this being maintained any longer?
It’s the only Js blocker for Safari I know of that’s still partially effective.

AFAIK it does NOT offer the ability to add exceptions, despite the description saying it does:
**"A Safari Extension that blocks all third party scripts, but lets you add exceptions."**

It doesn’t block ANY scripts on some sites, like https://kickass.cd.
Clicking anywhere on the page causes new, fullsize spam windows to open with addresses like http://ssl2anyone2.com/watch?key=a17a1b709ad947538e1ab0c89c59c098&kw=%5B%22kat%22%2C%22-%22%2C%22kickass%22%2C%22torrents%22%5D&refer=https%3A%2F%2Fkickass.cd%2F&scrWidth=1920&scrHeight=1200&tz=-7

I’ve added **ssl2anyone2.com** to my hosts menu so the pages won’t load, but that doesn’t stop the windows from opening.

**Comment by yene** [comment]
hi,
The third party blocking provided by safari makes it so javascript files from external domains are not loaded. In some cases this was too restrictive (for example youtube embeds) and in some cases useless (when sites host their own advertisement).

Try ublock origin for safari. https://github.com/el1t/uBlock-Safari
